DECLARE
    v_count NUMBER;

    PROCEDURE create_table_if_missing(p_table_name IN VARCHAR2, p_ddl IN CLOB) IS
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM user_tables
        WHERE table_name = UPPER(p_table_name);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
        END IF;
    END;

    PROCEDURE add_column_if_missing(p_table_name IN VARCHAR2, p_column_name IN VARCHAR2, p_definition IN VARCHAR2) IS
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM user_tab_columns
        WHERE table_name = UPPER(p_table_name)
          AND column_name = UPPER(p_column_name);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table_name || ' ADD (' || p_definition || ')';
        END IF;
    END;

    PROCEDURE add_index_if_missing(p_index_name IN VARCHAR2, p_ddl IN VARCHAR2) IS
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM user_indexes
        WHERE index_name = UPPER(p_index_name);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
        END IF;
    END;

    PROCEDURE drop_constraint_if_exists(p_table_name IN VARCHAR2, p_constraint_name IN VARCHAR2) IS
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM user_constraints
        WHERE table_name = UPPER(p_table_name)
          AND constraint_name = UPPER(p_constraint_name);

        IF v_count > 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table_name || ' DROP CONSTRAINT ' || p_constraint_name;
        END IF;
    END;

    PROCEDURE add_constraint_if_missing(p_table_name IN VARCHAR2, p_constraint_name IN VARCHAR2, p_definition IN VARCHAR2) IS
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM user_constraints
        WHERE table_name = UPPER(p_table_name)
          AND constraint_name = UPPER(p_constraint_name);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table_name || ' ADD CONSTRAINT ' || p_constraint_name || ' ' || p_definition;
        END IF;
    END;

    PROCEDURE normalize_boolean_column(p_table_name IN VARCHAR2, p_column_name IN VARCHAR2, p_default IN NUMBER) IS
    BEGIN
        EXECUTE IMMEDIATE 'UPDATE ' || p_table_name || ' SET ' || p_column_name || ' = ' || p_default ||
                          ' WHERE ' || p_column_name || ' IS NULL';
        EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table_name || ' MODIFY (' || p_column_name ||
                          ' DEFAULT ' || p_default || ' NOT NULL)';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE NOT IN (-904, -1442) THEN
                RAISE;
            END IF;
    END;

    PROCEDURE replace_column_check(
        p_table_name IN VARCHAR2,
        p_column_name IN VARCHAR2,
        p_constraint_name IN VARCHAR2,
        p_definition IN VARCHAR2
    ) IS
    BEGIN
        FOR c IN (
            SELECT uc.constraint_name
            FROM user_constraints uc
            JOIN user_cons_columns ucc ON uc.constraint_name = ucc.constraint_name
            WHERE uc.table_name = UPPER(p_table_name)
              AND ucc.table_name = UPPER(p_table_name)
              AND ucc.column_name = UPPER(p_column_name)
              AND uc.constraint_type = 'C'
              AND NVL(UPPER(uc.search_condition_vc), ' ') NOT LIKE '%' || UPPER(p_column_name) || ' IS NOT NULL%'
        ) LOOP
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table_name || ' DROP CONSTRAINT ' || c.constraint_name;
        END LOOP;

        add_constraint_if_missing(p_table_name, p_constraint_name, p_definition);
    END;
BEGIN
    create_table_if_missing('users', q'[
        CREATE TABLE users (
            id NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
            email VARCHAR2(255 CHAR),
            password VARCHAR2(255 CHAR),
            username VARCHAR2(255 CHAR) NOT NULL,
            foto_capa VARCHAR2(255 CHAR),
            foto_perfil VARCHAR2(255 CHAR),
            bio VARCHAR2(255 CHAR),
            admin NUMBER(1,0) DEFAULT 0 NOT NULL,
            banned NUMBER(1,0) DEFAULT 0 NOT NULL,
            CONSTRAINT pk_users PRIMARY KEY (id),
            CONSTRAINT uk_users_email UNIQUE (email),
            CONSTRAINT uk_users_username UNIQUE (username)
        )
    ]');

    create_table_if_missing('beaches', q'[
        CREATE TABLE beaches (
            id NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
            nome VARCHAR2(255 CHAR) NOT NULL,
            descricao CLOB,
            localizacao VARCHAR2(255 CHAR) NOT NULL,
            caminho_foto VARCHAR2(255 CHAR),
            nivel_experiencia VARCHAR2(255 CHAR),
            latitude FLOAT(53),
            longitude FLOAT(53),
            CONSTRAINT pk_beaches PRIMARY KEY (id)
        )
    ]');

    create_table_if_missing('conversations', q'[
        CREATE TABLE conversations (
            id VARCHAR2(36 CHAR) NOT NULL,
            created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
            is_group NUMBER(1,0) DEFAULT 0 NOT NULL,
            CONSTRAINT pk_conversations PRIMARY KEY (id)
        )
    ]');

    create_table_if_missing('points_of_interest', q'[
        CREATE TABLE points_of_interest (
            id NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
            nome VARCHAR2(255 CHAR) NOT NULL,
            descricao CLOB,
            categoria VARCHAR2(255 CHAR) NOT NULL,
            latitude FLOAT(53) NOT NULL,
            longitude FLOAT(53) NOT NULL,
            telefone VARCHAR2(255 CHAR),
            caminho_foto VARCHAR2(255 CHAR),
            CONSTRAINT pk_points_of_interest PRIMARY KEY (id)
        )
    ]');

    create_table_if_missing('admin_audit_logs', q'[
        CREATE TABLE admin_audit_logs (
            id NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
            actor_email VARCHAR2(255 CHAR) NOT NULL,
            action VARCHAR2(255 CHAR) NOT NULL,
            target_type VARCHAR2(255 CHAR) NOT NULL,
            target_id NUMBER(19,0) NOT NULL,
            details VARCHAR2(255 CHAR),
            created_at TIMESTAMP(6) NOT NULL,
            CONSTRAINT pk_admin_audit_logs PRIMARY KEY (id)
        )
    ]');

    create_table_if_missing('password_reset_tokens', q'[
        CREATE TABLE password_reset_tokens (
            id NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
            token VARCHAR2(255 CHAR) NOT NULL,
            user_id NUMBER(19,0) NOT NULL,
            expiry_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
            CONSTRAINT pk_password_reset_tokens PRIMARY KEY (id),
            CONSTRAINT uk_password_reset_tokens_token UNIQUE (token),
            CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
        )
    ]');

    create_table_if_missing('posts', q'[
        CREATE TABLE posts (
            id NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
            descricao VARCHAR2(255 CHAR) NOT NULL,
            publico NUMBER(1,0) DEFAULT 1 NOT NULL,
            caminho_foto VARCHAR2(255 CHAR),
            data TIMESTAMP(6) NOT NULL,
            usuario_id NUMBER(19,0) NOT NULL,
            beach_id NUMBER(19,0),
            CONSTRAINT pk_posts PRIMARY KEY (id),
            CONSTRAINT fk_posts_usuario FOREIGN KEY (usuario_id) REFERENCES users (id),
            CONSTRAINT fk_posts_beach FOREIGN KEY (beach_id) REFERENCES beaches (id)
        )
    ]');

    create_table_if_missing('comments', q'[
        CREATE TABLE comments (
            id NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
            texto VARCHAR2(255 CHAR) NOT NULL,
            data TIMESTAMP(6) NOT NULL,
            usuario_id NUMBER(19,0) NOT NULL,
            post_id NUMBER(19,0) NOT NULL,
            parent_id NUMBER(19,0),
            CONSTRAINT pk_comments PRIMARY KEY (id),
            CONSTRAINT fk_comments_usuario FOREIGN KEY (usuario_id) REFERENCES users (id),
            CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts (id),
            CONSTRAINT fk_comments_parent FOREIGN KEY (parent_id) REFERENCES comments (id)
        )
    ]');

    create_table_if_missing('likes', q'[
        CREATE TABLE likes (
            id NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
            post_id NUMBER(19,0) NOT NULL,
            usuario_id NUMBER(19,0) NOT NULL,
            data TIMESTAMP(6) NOT NULL,
            CONSTRAINT pk_likes PRIMARY KEY (id),
            CONSTRAINT uk_likes_post_usuario UNIQUE (post_id, usuario_id),
            CONSTRAINT fk_likes_post FOREIGN KEY (post_id) REFERENCES posts (id),
            CONSTRAINT fk_likes_usuario FOREIGN KEY (usuario_id) REFERENCES users (id)
        )
    ]');

    create_table_if_missing('mensagens', q'[
        CREATE TABLE mensagens (
            id NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
            texto CLOB NOT NULL,
            data TIMESTAMP(6) NOT NULL,
            autor_id NUMBER(19,0) NOT NULL,
            praia_id NUMBER(19,0) NOT NULL,
            CONSTRAINT pk_mensagens PRIMARY KEY (id),
            CONSTRAINT fk_mensagens_autor FOREIGN KEY (autor_id) REFERENCES users (id),
            CONSTRAINT fk_mensagens_praia FOREIGN KEY (praia_id) REFERENCES beaches (id)
        )
    ]');

    create_table_if_missing('notifications', q'[
        CREATE TABLE notifications (
            id NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
            recipient_id NUMBER(19,0) NOT NULL,
            sender_id NUMBER(19,0) NOT NULL,
            type VARCHAR2(255 CHAR) NOT NULL,
            post_id NUMBER(19,0),
            comment_id NUMBER(19,0),
            is_read NUMBER(1,0) DEFAULT 0 NOT NULL,
            read NUMBER(1,0) DEFAULT 0 NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            CONSTRAINT pk_notifications PRIMARY KEY (id),
            CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_id) REFERENCES users (id),
            CONSTRAINT fk_notifications_sender FOREIGN KEY (sender_id) REFERENCES users (id),
            CONSTRAINT fk_notifications_post FOREIGN KEY (post_id) REFERENCES posts (id),
            CONSTRAINT fk_notifications_comment FOREIGN KEY (comment_id) REFERENCES comments (id)
        )
    ]');

    create_table_if_missing('push_tokens', q'[
        CREATE TABLE push_tokens (
            id NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
            user_id NUMBER(19,0) NOT NULL,
            push_token VARCHAR2(512 CHAR) NOT NULL,
            platform VARCHAR2(32 CHAR) NOT NULL,
            is_active NUMBER(1,0) DEFAULT 1 NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            last_used_at TIMESTAMP(6),
            CONSTRAINT pk_push_tokens PRIMARY KEY (id),
            CONSTRAINT uk_push_tokens_token UNIQUE (push_token),
            CONSTRAINT fk_push_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
        )
    ]');

    create_table_if_missing('messages', q'[
        CREATE TABLE messages (
            id VARCHAR2(36 CHAR) NOT NULL,
            conversation_id VARCHAR2(36 CHAR) NOT NULL,
            sender_id VARCHAR2(255 CHAR) NOT NULL,
            content CLOB,
            attachment_url VARCHAR2(255 CHAR),
            created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
            edited_at TIMESTAMP(6) WITH TIME ZONE,
            CONSTRAINT pk_messages PRIMARY KEY (id)
        )
    ]');

    create_table_if_missing('conversation_participants', q'[
        CREATE TABLE conversation_participants (
            conversation_id VARCHAR2(255 CHAR) NOT NULL,
            user_id VARCHAR2(255 CHAR) NOT NULL,
            last_read_at TIMESTAMP(6) WITH TIME ZONE,
            CONSTRAINT pk_conversation_participants PRIMARY KEY (conversation_id, user_id)
        )
    ]');

    create_table_if_missing('user_seguindo', q'[
        CREATE TABLE user_seguindo (
            user_id NUMBER(19,0) NOT NULL,
            seguindo_id NUMBER(19,0) NOT NULL,
            CONSTRAINT pk_user_seguindo PRIMARY KEY (user_id, seguindo_id),
            CONSTRAINT fk_user_seguindo_user FOREIGN KEY (user_id) REFERENCES users (id),
            CONSTRAINT fk_user_seguindo_seguindo FOREIGN KEY (seguindo_id) REFERENCES users (id)
        )
    ]');

    add_column_if_missing('users', 'admin', 'admin NUMBER(1,0) DEFAULT 0 NOT NULL');
    add_column_if_missing('users', 'banned', 'banned NUMBER(1,0) DEFAULT 0 NOT NULL');
    add_column_if_missing('beaches', 'latitude', 'latitude FLOAT(53)');
    add_column_if_missing('beaches', 'longitude', 'longitude FLOAT(53)');
    add_column_if_missing('posts', 'publico', 'publico NUMBER(1,0) DEFAULT 1 NOT NULL');
    add_column_if_missing('conversations', 'is_group', 'is_group NUMBER(1,0) DEFAULT 0 NOT NULL');
    add_column_if_missing('notifications', 'is_read', 'is_read NUMBER(1,0) DEFAULT 0 NOT NULL');
    add_column_if_missing('notifications', 'read', 'read NUMBER(1,0) DEFAULT 0 NOT NULL');
    add_column_if_missing('push_tokens', 'is_active', 'is_active NUMBER(1,0) DEFAULT 1 NOT NULL');

    normalize_boolean_column('users', 'admin', 0);
    normalize_boolean_column('users', 'banned', 0);
    normalize_boolean_column('posts', 'publico', 1);
    normalize_boolean_column('notifications', 'is_read', 0);
    normalize_boolean_column('notifications', 'read', 0);
    normalize_boolean_column('push_tokens', 'is_active', 1);
    normalize_boolean_column('conversations', 'is_group', 0);

    replace_column_check(
        'notifications',
        'type',
        'chk_notifications_type',
        q'[CHECK (type IN ('MENTION','LIKE','COMMENT','REPLY','FOLLOW'))]'
    );

    replace_column_check(
        'points_of_interest',
        'categoria',
        'chk_points_of_interest_categoria',
        q'[CHECK (categoria IN ('SURF_SCHOOL','SWIMMING_SCHOOL','SURF_SHOP','BOARD_REPAIR','TOURIST_SPOT'))]'
    );

    add_index_if_missing('idx_push_tokens_user_id',
        'CREATE INDEX idx_push_tokens_user_id ON push_tokens (user_id)');
    add_index_if_missing('idx_push_tokens_user_active',
        'CREATE INDEX idx_push_tokens_user_active ON push_tokens (user_id, is_active)');
END;
/
